// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header carries per-batch metadata: the operation timestamp and an
// optional transaction context. Every request in the batch inherits
// these values unless it overrides them (not implemented yet).
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *Timestamp             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn           *TxnMeta               `protobuf:"bytes,2,opt,name=txn,proto3" json:"txn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_internal_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Header) GetTxn() *TxnMeta {
	if x != nil {
		return x.Txn
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{4}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{6}
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	MaxKeys       int64                  `protobuf:"varint,3,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *ScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ScanRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ScanRequest) GetMaxKeys() int64 {
	if x != nil {
		return x.MaxKeys
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*KeyValue            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *ScanResponse) GetRows() []*KeyValue {
	if x != nil {
		return x.Rows
	}
	return nil
}

// RequestUnion wraps one KV operation. The oneof ensures exactly one
// request type is set per slot in a BatchRequest.
type RequestUnion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RequestUnion_Get
	//	*RequestUnion_Put
	//	*RequestUnion_Delete
	//	*RequestUnion_Scan
	Value         isRequestUnion_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUnion) Reset() {
	*x = RequestUnion{}
	mi := &file_internal_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUnion) ProtoMessage() {}

func (x *RequestUnion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUnion.ProtoReflect.Descriptor instead.
func (*RequestUnion) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *RequestUnion) GetValue() isRequestUnion_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RequestUnion) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Value.(*RequestUnion_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *RequestUnion) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Value.(*RequestUnion_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *RequestUnion) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Value.(*RequestUnion_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RequestUnion) GetScan() *ScanRequest {
	if x != nil {
		if x, ok := x.Value.(*RequestUnion_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

type isRequestUnion_Value interface {
	isRequestUnion_Value()
}

type RequestUnion_Get struct {
	Get *GetRequest `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type RequestUnion_Put struct {
	Put *PutRequest `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type RequestUnion_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type RequestUnion_Scan struct {
	Scan *ScanRequest `protobuf:"bytes,4,opt,name=scan,proto3,oneof"`
}

func (*RequestUnion_Get) isRequestUnion_Value() {}

func (*RequestUnion_Put) isRequestUnion_Value() {}

func (*RequestUnion_Delete) isRequestUnion_Value() {}

func (*RequestUnion_Scan) isRequestUnion_Value() {}

// ResponseUnion wraps one KV response, matching the request at the
// same index in the BatchRequest.
type ResponseUnion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ResponseUnion_Get
	//	*ResponseUnion_Put
	//	*ResponseUnion_Delete
	//	*ResponseUnion_Scan
	Value         isResponseUnion_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseUnion) Reset() {
	*x = ResponseUnion{}
	mi := &file_internal_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUnion) ProtoMessage() {}

func (x *ResponseUnion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUnion.ProtoReflect.Descriptor instead.
func (*ResponseUnion) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseUnion) GetValue() isResponseUnion_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ResponseUnion) GetGet() *GetResponse {
	if x != nil {
		if x, ok := x.Value.(*ResponseUnion_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *ResponseUnion) GetPut() *PutResponse {
	if x != nil {
		if x, ok := x.Value.(*ResponseUnion_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *ResponseUnion) GetDelete() *DeleteResponse {
	if x != nil {
		if x, ok := x.Value.(*ResponseUnion_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *ResponseUnion) GetScan() *ScanResponse {
	if x != nil {
		if x, ok := x.Value.(*ResponseUnion_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

type isResponseUnion_Value interface {
	isResponseUnion_Value()
}

type ResponseUnion_Get struct {
	Get *GetResponse `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type ResponseUnion_Put struct {
	Put *PutResponse `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type ResponseUnion_Delete struct {
	Delete *DeleteResponse `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type ResponseUnion_Scan struct {
	Scan *ScanResponse `protobuf:"bytes,4,opt,name=scan,proto3,oneof"`
}

func (*ResponseUnion_Get) isResponseUnion_Value() {}

func (*ResponseUnion_Put) isResponseUnion_Value() {}

func (*ResponseUnion_Delete) isResponseUnion_Value() {}

func (*ResponseUnion_Scan) isResponseUnion_Value() {}

// BatchRequest bundles multiple KV operations into a single RPC call.
// The server executes each request sequentially and returns responses
// in the same order.
type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Requests      []*RequestUnion        `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *BatchRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BatchRequest) GetRequests() []*RequestUnion {
	if x != nil {
		return x.Requests
	}
	return nil
}

// BatchResponse contains one response per request, in order. If any
// request fails, the error field is set and remaining responses may
// be absent.
type BatchResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Responses []*ResponseUnion       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Error     *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Set (with responses empty) when this node is not the leader. The client
	// should redirect to leader_address. Same shape is returned by ExecSQL.
	NotLeader     *NotLeaderError `protobuf:"bytes,3,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *BatchResponse) GetResponses() []*ResponseUnion {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *BatchResponse) GetNotLeader() *NotLeaderError {
	if x != nil {
		return x.NotLeader
	}
	return nil
}

// NotLeaderError tells a client that reached a non-leader where the leader is,
// so it can redirect rather than guess. Under M4's leader-is-leaseholder
// simplification the leader is the only replica that serves reads and writes.
type NotLeaderError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderNodeId  uint64                 `protobuf:"varint,1,opt,name=leader_node_id,json=leaderNodeId,proto3" json:"leader_node_id,omitempty"` // 0 if no leader is currently known
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"` // resolved via gossip; empty if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeaderError) Reset() {
	*x = NotLeaderError{}
	mi := &file_internal_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeaderError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeaderError) ProtoMessage() {}

func (x *NotLeaderError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeaderError.ProtoReflect.Descriptor instead.
func (*NotLeaderError) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *NotLeaderError) GetLeaderNodeId() uint64 {
	if x != nil {
		return x.LeaderNodeId
	}
	return 0
}

func (x *NotLeaderError) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

var File_internal_proto_api_proto protoreflect.FileDescriptor

const file_internal_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/api.proto\x12\x10ducklingdb.proto\x1a\x19internal/proto/data.proto\"p\n" +
	"\x06Header\x129\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1b.ducklingdb.proto.TimestampR\ttimestamp\x12+\n" +
	"\x03txn\x18\x02 \x01(\v2\x19.ducklingdb.proto.TxnMetaR\x03txn\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"<\n" +
	"\vGetResponse\x12-\n" +
	"\x05value\x18\x01 \x01(\v2\x17.ducklingdb.proto.ValueR\x05value\"M\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.ducklingdb.proto.ValueR\x05value\"\r\n" +
	"\vPutResponse\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"^\n" +
	"\vScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\x12\x19\n" +
	"\bmax_keys\x18\x03 \x01(\x03R\amaxKeys\">\n" +
	"\fScanResponse\x12.\n" +
	"\x04rows\x18\x01 \x03(\v2\x1a.ducklingdb.proto.KeyValueR\x04rows\"\xeb\x01\n" +
	"\fRequestUnion\x120\n" +
	"\x03get\x18\x01 \x01(\v2\x1c.ducklingdb.proto.GetRequestH\x00R\x03get\x120\n" +
	"\x03put\x18\x02 \x01(\v2\x1c.ducklingdb.proto.PutRequestH\x00R\x03put\x129\n" +
	"\x06delete\x18\x03 \x01(\v2\x1f.ducklingdb.proto.DeleteRequestH\x00R\x06delete\x123\n" +
	"\x04scan\x18\x04 \x01(\v2\x1d.ducklingdb.proto.ScanRequestH\x00R\x04scanB\a\n" +
	"\x05value\"\xf0\x01\n" +
	"\rResponseUnion\x121\n" +
	"\x03get\x18\x01 \x01(\v2\x1d.ducklingdb.proto.GetResponseH\x00R\x03get\x121\n" +
	"\x03put\x18\x02 \x01(\v2\x1d.ducklingdb.proto.PutResponseH\x00R\x03put\x12:\n" +
	"\x06delete\x18\x03 \x01(\v2 .ducklingdb.proto.DeleteResponseH\x00R\x06delete\x124\n" +
	"\x04scan\x18\x04 \x01(\v2\x1e.ducklingdb.proto.ScanResponseH\x00R\x04scanB\a\n" +
	"\x05value\"|\n" +
	"\fBatchRequest\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x18.ducklingdb.proto.HeaderR\x06header\x12:\n" +
	"\brequests\x18\x02 \x03(\v2\x1e.ducklingdb.proto.RequestUnionR\brequests\"\xbe\x01\n" +
	"\rBatchResponse\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.ducklingdb.proto.ResponseUnionR\tresponses\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.ducklingdb.proto.ErrorR\x05error\x12?\n" +
	"\n" +
	"not_leader\x18\x03 \x01(\v2 .ducklingdb.proto.NotLeaderErrorR\tnotLeader\"]\n" +
	"\x0eNotLeaderError\x12$\n" +
	"\x0eleader_node_id\x18\x01 \x01(\x04R\fleaderNodeId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddressB0Z.github.com/duchm1606/ducklingdb/internal/protob\x06proto3"

var (
	file_internal_proto_api_proto_rawDescOnce sync.Once
	file_internal_proto_api_proto_rawDescData []byte
)

func file_internal_proto_api_proto_rawDescGZIP() []byte {
	file_internal_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)))
	})
	return file_internal_proto_api_proto_rawDescData
}

var file_internal_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_proto_api_proto_goTypes = []any{
	(*Header)(nil),         // 0: ducklingdb.proto.Header
	(*GetRequest)(nil),     // 1: ducklingdb.proto.GetRequest
	(*GetResponse)(nil),    // 2: ducklingdb.proto.GetResponse
	(*PutRequest)(nil),     // 3: ducklingdb.proto.PutRequest
	(*PutResponse)(nil),    // 4: ducklingdb.proto.PutResponse
	(*DeleteRequest)(nil),  // 5: ducklingdb.proto.DeleteRequest
	(*DeleteResponse)(nil), // 6: ducklingdb.proto.DeleteResponse
	(*ScanRequest)(nil),    // 7: ducklingdb.proto.ScanRequest
	(*ScanResponse)(nil),   // 8: ducklingdb.proto.ScanResponse
	(*RequestUnion)(nil),   // 9: ducklingdb.proto.RequestUnion
	(*ResponseUnion)(nil),  // 10: ducklingdb.proto.ResponseUnion
	(*BatchRequest)(nil),   // 11: ducklingdb.proto.BatchRequest
	(*BatchResponse)(nil),  // 12: ducklingdb.proto.BatchResponse
	(*NotLeaderError)(nil), // 13: ducklingdb.proto.NotLeaderError
	(*Timestamp)(nil),      // 14: ducklingdb.proto.Timestamp
	(*TxnMeta)(nil),        // 15: ducklingdb.proto.TxnMeta
	(*Value)(nil),          // 16: ducklingdb.proto.Value
	(*KeyValue)(nil),       // 17: ducklingdb.proto.KeyValue
	(*Error)(nil),          // 18: ducklingdb.proto.Error
}
var file_internal_proto_api_proto_depIdxs = []int32{
	14, // 0: ducklingdb.proto.Header.timestamp:type_name -> ducklingdb.proto.Timestamp
	15, // 1: ducklingdb.proto.Header.txn:type_name -> ducklingdb.proto.TxnMeta
	16, // 2: ducklingdb.proto.GetResponse.value:type_name -> ducklingdb.proto.Value
	16, // 3: ducklingdb.proto.PutRequest.value:type_name -> ducklingdb.proto.Value
	17, // 4: ducklingdb.proto.ScanResponse.rows:type_name -> ducklingdb.proto.KeyValue
	1,  // 5: ducklingdb.proto.RequestUnion.get:type_name -> ducklingdb.proto.GetRequest
	3,  // 6: ducklingdb.proto.RequestUnion.put:type_name -> ducklingdb.proto.PutRequest
	5,  // 7: ducklingdb.proto.RequestUnion.delete:type_name -> ducklingdb.proto.DeleteRequest
	7,  // 8: ducklingdb.proto.RequestUnion.scan:type_name -> ducklingdb.proto.ScanRequest
	2,  // 9: ducklingdb.proto.ResponseUnion.get:type_name -> ducklingdb.proto.GetResponse
	4,  // 10: ducklingdb.proto.ResponseUnion.put:type_name -> ducklingdb.proto.PutResponse
	6,  // 11: ducklingdb.proto.ResponseUnion.delete:type_name -> ducklingdb.proto.DeleteResponse
	8,  // 12: ducklingdb.proto.ResponseUnion.scan:type_name -> ducklingdb.proto.ScanResponse
	0,  // 13: ducklingdb.proto.BatchRequest.header:type_name -> ducklingdb.proto.Header
	9,  // 14: ducklingdb.proto.BatchRequest.requests:type_name -> ducklingdb.proto.RequestUnion
	10, // 15: ducklingdb.proto.BatchResponse.responses:type_name -> ducklingdb.proto.ResponseUnion
	18, // 16: ducklingdb.proto.BatchResponse.error:type_name -> ducklingdb.proto.Error
	13, // 17: ducklingdb.proto.BatchResponse.not_leader:type_name -> ducklingdb.proto.NotLeaderError
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_proto_api_proto_init() }
func file_internal_proto_api_proto_init() {
	if File_internal_proto_api_proto != nil {
		return
	}
	file_internal_proto_data_proto_init()
	file_internal_proto_api_proto_msgTypes[9].OneofWrappers = []any{
		(*RequestUnion_Get)(nil),
		(*RequestUnion_Put)(nil),
		(*RequestUnion_Delete)(nil),
		(*RequestUnion_Scan)(nil),
	}
	file_internal_proto_api_proto_msgTypes[10].OneofWrappers = []any{
		(*ResponseUnion_Get)(nil),
		(*ResponseUnion_Put)(nil),
		(*ResponseUnion_Delete)(nil),
		(*ResponseUnion_Scan)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_proto_api_proto_depIdxs,
		MessageInfos:      file_internal_proto_api_proto_msgTypes,
	}.Build()
	File_internal_proto_api_proto = out.File
	file_internal_proto_api_proto_goTypes = nil
	file_internal_proto_api_proto_depIdxs = nil
}
