// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Timestamp mirrors hlc.Timestamp — a hybrid logical clock value
// with a wall-clock component (nanoseconds) and a logical counter.
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      int64                  `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Logical       int32                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_internal_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_internal_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Timestamp) GetLogical() int32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

// TxnMeta is the wire representation of a transaction's identity and
// current state. It carries enough information for a remote node to
// participate in conflict resolution without a round-trip to the
// transaction record.
type TxnMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                // 16-byte TxnID
	Status         int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`       // 0=PENDING, 1=COMMITTED, 2=ABORTED
	Isolation      int32                  `protobuf:"varint,3,opt,name=isolation,proto3" json:"isolation,omitempty"` // 0=SSI, 1=SI
	ReadTimestamp  *Timestamp             `protobuf:"bytes,4,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	WriteTimestamp *Timestamp             `protobuf:"bytes,5,opt,name=write_timestamp,json=writeTimestamp,proto3" json:"write_timestamp,omitempty"`
	MaxTimestamp   *Timestamp             `protobuf:"bytes,6,opt,name=max_timestamp,json=maxTimestamp,proto3" json:"max_timestamp,omitempty"`
	Priority       int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TxnMeta) Reset() {
	*x = TxnMeta{}
	mi := &file_internal_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnMeta) ProtoMessage() {}

func (x *TxnMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnMeta.ProtoReflect.Descriptor instead.
func (*TxnMeta) Descriptor() ([]byte, []int) {
	return file_internal_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *TxnMeta) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TxnMeta) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TxnMeta) GetIsolation() int32 {
	if x != nil {
		return x.Isolation
	}
	return 0
}

func (x *TxnMeta) GetReadTimestamp() *Timestamp {
	if x != nil {
		return x.ReadTimestamp
	}
	return nil
}

func (x *TxnMeta) GetWriteTimestamp() *Timestamp {
	if x != nil {
		return x.WriteTimestamp
	}
	return nil
}

func (x *TxnMeta) GetMaxTimestamp() *Timestamp {
	if x != nil {
		return x.MaxTimestamp
	}
	return nil
}

func (x *TxnMeta) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Value wraps raw bytes with an optional timestamp, used in
// KV responses to return both the data and its version.
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawBytes      []byte                 `protobuf:"bytes,1,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_internal_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_internal_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

func (x *Value) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// KeyValue is a single key-value pair returned by Scan operations.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_internal_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_internal_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Error carries a structured error from the server back to the client.
// For now it's a simple string; future milestones may add typed error
// variants (WriteIntentError, WriteTooOldError, etc.).
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_data_proto protoreflect.FileDescriptor

const file_internal_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/data.proto\x12\x10ducklingdb.proto\"B\n" +
	"\tTimestamp\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x05R\alogical\"\xb7\x02\n" +
	"\aTxnMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1c\n" +
	"\tisolation\x18\x03 \x01(\x05R\tisolation\x12B\n" +
	"\x0eread_timestamp\x18\x04 \x01(\v2\x1b.ducklingdb.proto.TimestampR\rreadTimestamp\x12D\n" +
	"\x0fwrite_timestamp\x18\x05 \x01(\v2\x1b.ducklingdb.proto.TimestampR\x0ewriteTimestamp\x12@\n" +
	"\rmax_timestamp\x18\x06 \x01(\v2\x1b.ducklingdb.proto.TimestampR\fmaxTimestamp\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"_\n" +
	"\x05Value\x12\x1b\n" +
	"\traw_bytes\x18\x01 \x01(\fR\brawBytes\x129\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1b.ducklingdb.proto.TimestampR\ttimestamp\"K\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.ducklingdb.proto.ValueR\x05value\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB0Z.github.com/duchm1606/ducklingdb/internal/protob\x06proto3"

var (
	file_internal_proto_data_proto_rawDescOnce sync.Once
	file_internal_proto_data_proto_rawDescData []byte
)

func file_internal_proto_data_proto_rawDescGZIP() []byte {
	file_internal_proto_data_proto_rawDescOnce.Do(func() {
		file_internal_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_data_proto_rawDesc), len(file_internal_proto_data_proto_rawDesc)))
	})
	return file_internal_proto_data_proto_rawDescData
}

var file_internal_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_data_proto_goTypes = []any{
	(*Timestamp)(nil), // 0: ducklingdb.proto.Timestamp
	(*TxnMeta)(nil),   // 1: ducklingdb.proto.TxnMeta
	(*Value)(nil),     // 2: ducklingdb.proto.Value
	(*KeyValue)(nil),  // 3: ducklingdb.proto.KeyValue
	(*Error)(nil),     // 4: ducklingdb.proto.Error
}
var file_internal_proto_data_proto_depIdxs = []int32{
	0, // 0: ducklingdb.proto.TxnMeta.read_timestamp:type_name -> ducklingdb.proto.Timestamp
	0, // 1: ducklingdb.proto.TxnMeta.write_timestamp:type_name -> ducklingdb.proto.Timestamp
	0, // 2: ducklingdb.proto.TxnMeta.max_timestamp:type_name -> ducklingdb.proto.Timestamp
	0, // 3: ducklingdb.proto.Value.timestamp:type_name -> ducklingdb.proto.Timestamp
	2, // 4: ducklingdb.proto.KeyValue.value:type_name -> ducklingdb.proto.Value
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_data_proto_init() }
func file_internal_proto_data_proto_init() {
	if File_internal_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_data_proto_rawDesc), len(file_internal_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_data_proto_goTypes,
		DependencyIndexes: file_internal_proto_data_proto_depIdxs,
		MessageInfos:      file_internal_proto_data_proto_msgTypes,
	}.Build()
	File_internal_proto_data_proto = out.File
	file_internal_proto_data_proto_goTypes = nil
	file_internal_proto_data_proto_depIdxs = nil
}
