// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeDescriptor describes a single DucklingDB node. Gossiped to all
// nodes so every member knows how to reach every other member.
type NodeDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                                                       // "host:port"
	Attrs         map[string]string      `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // locality labels, custom tags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDescriptor) Reset() {
	*x = NodeDescriptor{}
	mi := &file_internal_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDescriptor) ProtoMessage() {}

func (x *NodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDescriptor.ProtoReflect.Descriptor instead.
func (*NodeDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDescriptor) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeDescriptor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeDescriptor) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// StoreCapacity summarizes a store's resource usage. Gossiped
// periodically for the allocator (M4) to make placement decisions.
type StoreCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	RangeCount    int32                  `protobuf:"varint,3,opt,name=range_count,json=rangeCount,proto3" json:"range_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCapacity) Reset() {
	*x = StoreCapacity{}
	mi := &file_internal_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCapacity) ProtoMessage() {}

func (x *StoreCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCapacity.ProtoReflect.Descriptor instead.
func (*StoreCapacity) Descriptor() ([]byte, []int) {
	return file_internal_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *StoreCapacity) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StoreCapacity) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StoreCapacity) GetRangeCount() int32 {
	if x != nil {
		return x.RangeCount
	}
	return 0
}

// StoreDescriptor describes a single store (one engine instance).
// Each node has exactly one store in DucklingDB.
type StoreDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int32                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Capacity      *StoreCapacity         `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDescriptor) Reset() {
	*x = StoreDescriptor{}
	mi := &file_internal_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDescriptor) ProtoMessage() {}

func (x *StoreDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDescriptor.ProtoReflect.Descriptor instead.
func (*StoreDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *StoreDescriptor) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *StoreDescriptor) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StoreDescriptor) GetCapacity() *StoreCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

var File_internal_proto_metadata_proto protoreflect.FileDescriptor

const file_internal_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/metadata.proto\x12\x10ducklingdb.proto\"\xc0\x01\n" +
	"\x0eNodeDescriptor\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12A\n" +
	"\x05attrs\x18\x03 \x03(\v2+.ducklingdb.proto.NodeDescriptor.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\rStoreCapacity\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vrange_count\x18\x03 \x01(\x05R\n" +
	"rangeCount\"\x82\x01\n" +
	"\x0fStoreDescriptor\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x05R\astoreId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12;\n" +
	"\bcapacity\x18\x03 \x01(\v2\x1f.ducklingdb.proto.StoreCapacityR\bcapacityB0Z.github.com/duchm1606/ducklingdb/internal/protob\x06proto3"

var (
	file_internal_proto_metadata_proto_rawDescOnce sync.Once
	file_internal_proto_metadata_proto_rawDescData []byte
)

func file_internal_proto_metadata_proto_rawDescGZIP() []byte {
	file_internal_proto_metadata_proto_rawDescOnce.Do(func() {
		file_internal_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_metadata_proto_rawDesc), len(file_internal_proto_metadata_proto_rawDesc)))
	})
	return file_internal_proto_metadata_proto_rawDescData
}

var file_internal_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_metadata_proto_goTypes = []any{
	(*NodeDescriptor)(nil),  // 0: ducklingdb.proto.NodeDescriptor
	(*StoreCapacity)(nil),   // 1: ducklingdb.proto.StoreCapacity
	(*StoreDescriptor)(nil), // 2: ducklingdb.proto.StoreDescriptor
	nil,                     // 3: ducklingdb.proto.NodeDescriptor.AttrsEntry
}
var file_internal_proto_metadata_proto_depIdxs = []int32{
	3, // 0: ducklingdb.proto.NodeDescriptor.attrs:type_name -> ducklingdb.proto.NodeDescriptor.AttrsEntry
	1, // 1: ducklingdb.proto.StoreDescriptor.capacity:type_name -> ducklingdb.proto.StoreCapacity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_metadata_proto_init() }
func file_internal_proto_metadata_proto_init() {
	if File_internal_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_metadata_proto_rawDesc), len(file_internal_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_metadata_proto_goTypes,
		DependencyIndexes: file_internal_proto_metadata_proto_depIdxs,
		MessageInfos:      file_internal_proto_metadata_proto_msgTypes,
	}.Build()
	File_internal_proto_metadata_proto = out.File
	file_internal_proto_metadata_proto_goTypes = nil
	file_internal_proto_metadata_proto_depIdxs = nil
}
