// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/raft.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaftEntry is one entry in the Raft log, carried over the wire.
type RaftEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftEntry) Reset() {
	*x = RaftEntry{}
	mi := &file_internal_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEntry) ProtoMessage() {}

func (x *RaftEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEntry.ProtoReflect.Descriptor instead.
func (*RaftEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// RaftMessage is a Raft protocol message sent between replicas.
type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeId       uint64                 `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Term          uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LogTerm       uint64                 `protobuf:"varint,5,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"` // prevLogTerm (MsgApp) or candidate last log term (MsgVote)
	Index         uint64                 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`                    // prevLogIndex (MsgApp) or matchIndex (MsgAppResp)
	Commit        uint64                 `protobuf:"varint,7,opt,name=commit,proto3" json:"commit,omitempty"`                  // leaderCommit
	Type          uint32                 `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`                      // raft.MessageType cast to uint32
	Reject        bool                   `protobuf:"varint,9,opt,name=reject,proto3" json:"reject,omitempty"`
	RejectHint    uint64                 `protobuf:"varint,10,opt,name=reject_hint,json=rejectHint,proto3" json:"reject_hint,omitempty"` // follower's last log index for fast nextIndex backtrack
	Entries       []*RaftEntry           `protobuf:"bytes,11,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_internal_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RaftMessage) GetRangeId() uint64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *RaftMessage) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftMessage) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *RaftMessage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RaftMessage) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *RaftMessage) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

func (x *RaftMessage) GetEntries() []*RaftEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RaftMessageResponse is the empty acknowledgement from Step RPC.
type RaftMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageResponse) Reset() {
	*x = RaftMessageResponse{}
	mi := &file_internal_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageResponse) ProtoMessage() {}

func (x *RaftMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageResponse.ProtoReflect.Descriptor instead.
func (*RaftMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_raft_proto_rawDescGZIP(), []int{2}
}

var File_internal_proto_raft_proto protoreflect.FileDescriptor

const file_internal_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/raft.proto\x12\x10ducklingdb.proto\"I\n" +
	"\tRaftEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xad\x02\n" +
	"\vRaftMessage\x12\x19\n" +
	"\brange_id\x18\x01 \x01(\x04R\arangeId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x19\n" +
	"\blog_term\x18\x05 \x01(\x04R\alogTerm\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x04R\x05index\x12\x16\n" +
	"\x06commit\x18\a \x01(\x04R\x06commit\x12\x12\n" +
	"\x04type\x18\b \x01(\rR\x04type\x12\x16\n" +
	"\x06reject\x18\t \x01(\bR\x06reject\x12\x1f\n" +
	"\vreject_hint\x18\n" +
	" \x01(\x04R\n" +
	"rejectHint\x125\n" +
	"\aentries\x18\v \x03(\v2\x1b.ducklingdb.proto.RaftEntryR\aentries\"\x15\n" +
	"\x13RaftMessageResponseB0Z.github.com/duchm1606/ducklingdb/internal/protob\x06proto3"

var (
	file_internal_proto_raft_proto_rawDescOnce sync.Once
	file_internal_proto_raft_proto_rawDescData []byte
)

func file_internal_proto_raft_proto_rawDescGZIP() []byte {
	file_internal_proto_raft_proto_rawDescOnce.Do(func() {
		file_internal_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_raft_proto_rawDesc), len(file_internal_proto_raft_proto_rawDesc)))
	})
	return file_internal_proto_raft_proto_rawDescData
}

var file_internal_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_raft_proto_goTypes = []any{
	(*RaftEntry)(nil),           // 0: ducklingdb.proto.RaftEntry
	(*RaftMessage)(nil),         // 1: ducklingdb.proto.RaftMessage
	(*RaftMessageResponse)(nil), // 2: ducklingdb.proto.RaftMessageResponse
}
var file_internal_proto_raft_proto_depIdxs = []int32{
	0, // 0: ducklingdb.proto.RaftMessage.entries:type_name -> ducklingdb.proto.RaftEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_raft_proto_init() }
func file_internal_proto_raft_proto_init() {
	if File_internal_proto_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_raft_proto_rawDesc), len(file_internal_proto_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_raft_proto_goTypes,
		DependencyIndexes: file_internal_proto_raft_proto_depIdxs,
		MessageInfos:      file_internal_proto_raft_proto_msgTypes,
	}.Build()
	File_internal_proto_raft_proto = out.File
	file_internal_proto_raft_proto_goTypes = nil
	file_internal_proto_raft_proto_depIdxs = nil
}
