// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AllocateNodeIDRequest is sent by a node that wants to join the cluster.
type AllocateNodeIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateNodeIDRequest) Reset() {
	*x = AllocateNodeIDRequest{}
	mi := &file_internal_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateNodeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateNodeIDRequest) ProtoMessage() {}

func (x *AllocateNodeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateNodeIDRequest.ProtoReflect.Descriptor instead.
func (*AllocateNodeIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{0}
}

// AllocateNodeIDResponse carries the assigned NodeID and the cluster's UUID.
type AllocateNodeIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId     []byte                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // 16-byte cluster UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateNodeIDResponse) Reset() {
	*x = AllocateNodeIDResponse{}
	mi := &file_internal_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateNodeIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateNodeIDResponse) ProtoMessage() {}

func (x *AllocateNodeIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateNodeIDResponse.ProtoReflect.Descriptor instead.
func (*AllocateNodeIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateNodeIDResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AllocateNodeIDResponse) GetClusterId() []byte {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

// PingRequest carries the sender's identity and current HLC timestamp.
// The receiver uses the timestamp to measure clock offset.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerTime    *Timestamp             `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PingRequest) GetServerTime() *Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// PingResponse carries the responder's identity and current HLC
// timestamp back to the caller.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerTime    *Timestamp             `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PingResponse) GetServerTime() *Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type SQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLRequest) Reset() {
	*x = SQLRequest{}
	mi := &file_internal_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLRequest) ProtoMessage() {}

func (x *SQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLRequest.ProtoReflect.Descriptor instead.
func (*SQLRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *SQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type SQLRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLRow) Reset() {
	*x = SQLRow{}
	mi := &file_internal_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLRow) ProtoMessage() {}

func (x *SQLRow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLRow.ProtoReflect.Descriptor instead.
func (*SQLRow) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *SQLRow) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*SQLRow              `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLResponse) Reset() {
	*x = SQLResponse{}
	mi := &file_internal_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLResponse) ProtoMessage() {}

func (x *SQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLResponse.ProtoReflect.Descriptor instead.
func (*SQLResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *SQLResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *SQLResponse) GetRows() []*SQLRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *SQLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SQLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Info is a single piece of gossip data identified by a string key.
type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	OrigStamp     int64                  `protobuf:"varint,3,opt,name=orig_stamp,json=origStamp,proto3" json:"orig_stamp,omitempty"`    // monotonic sequence number from the originating node
	NodeId        int32                  `protobuf:"varint,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`             // which node created this info
	TtlSeconds    int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // time-to-live in seconds (0 = no expiry)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_internal_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *Info) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Info) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Info) GetOrigStamp() int64 {
	if x != nil {
		return x.OrigStamp
	}
	return 0
}

func (x *Info) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Info) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// GossipMessage is exchanged bidirectionally on a Gossip stream.
// Each side sends its delta (items the peer hasn't seen) and its
// current high-water stamps so the peer can compute the next delta.
type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Delta         map[string]*Info       `protobuf:"bytes,3,rep,name=delta,proto3" json:"delta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                            // key → info (only fresh items)
	HighWater     map[int32]int64        `protobuf:"bytes,4,rep,name=high_water,json=highWater,proto3" json:"high_water,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // nodeID → highest seq seen from that node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_internal_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *GossipMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *GossipMessage) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GossipMessage) GetDelta() map[string]*Info {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *GossipMessage) GetHighWater() map[int32]int64 {
	if x != nil {
		return x.HighWater
	}
	return nil
}

var File_internal_proto_service_proto protoreflect.FileDescriptor

const file_internal_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/service.proto\x12\x10ducklingdb.proto\x1a\x18internal/proto/api.proto\x1a\x19internal/proto/data.proto\x1a\x19internal/proto/raft.proto\"\x17\n" +
	"\x15AllocateNodeIDRequest\"P\n" +
	"\x16AllocateNodeIDResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\fR\tclusterId\"d\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12<\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1b.ducklingdb.proto.TimestampR\n" +
	"serverTime\"e\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12<\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1b.ducklingdb.proto.TimestampR\n" +
	"serverTime\"\x1e\n" +
	"\n" +
	"SQLRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\" \n" +
	"\x06SQLRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x85\x01\n" +
	"\vSQLResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12,\n" +
	"\x04rows\x18\x02 \x03(\v2\x18.ducklingdb.proto.SQLRowR\x04rows\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x87\x01\n" +
	"\x04Info\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"orig_stamp\x18\x03 \x01(\x03R\torigStamp\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\x05R\x06nodeId\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"\xdd\x02\n" +
	"\rGossipMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12@\n" +
	"\x05delta\x18\x03 \x03(\v2*.ducklingdb.proto.GossipMessage.DeltaEntryR\x05delta\x12M\n" +
	"\n" +
	"high_water\x18\x04 \x03(\v2..ducklingdb.proto.GossipMessage.HighWaterEntryR\thighWater\x1aP\n" +
	"\n" +
	"DeltaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.ducklingdb.proto.InfoR\x05value:\x028\x01\x1a<\n" +
	"\x0eHighWaterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xd5\x02\n" +
	"\bInternal\x12J\n" +
	"\x05Batch\x12\x1e.ducklingdb.proto.BatchRequest\x1a\x1f.ducklingdb.proto.BatchResponse\"\x00\x12L\n" +
	"\tHeartbeat\x12\x1d.ducklingdb.proto.PingRequest\x1a\x1e.ducklingdb.proto.PingResponse\"\x00\x12e\n" +
	"\x0eAllocateNodeID\x12'.ducklingdb.proto.AllocateNodeIDRequest\x1a(.ducklingdb.proto.AllocateNodeIDResponse\"\x00\x12H\n" +
	"\aExecSQL\x12\x1c.ducklingdb.proto.SQLRequest\x1a\x1d.ducklingdb.proto.SQLResponse\"\x002a\n" +
	"\rGossipService\x12P\n" +
	"\x06Gossip\x12\x1f.ducklingdb.proto.GossipMessage\x1a\x1f.ducklingdb.proto.GossipMessage\"\x00(\x010\x012]\n" +
	"\vRaftService\x12N\n" +
	"\x04Step\x12\x1d.ducklingdb.proto.RaftMessage\x1a%.ducklingdb.proto.RaftMessageResponse\"\x00B0Z.github.com/duchm1606/ducklingdb/internal/protob\x06proto3"

var (
	file_internal_proto_service_proto_rawDescOnce sync.Once
	file_internal_proto_service_proto_rawDescData []byte
)

func file_internal_proto_service_proto_rawDescGZIP() []byte {
	file_internal_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_service_proto_rawDesc), len(file_internal_proto_service_proto_rawDesc)))
	})
	return file_internal_proto_service_proto_rawDescData
}

var file_internal_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_service_proto_goTypes = []any{
	(*AllocateNodeIDRequest)(nil),  // 0: ducklingdb.proto.AllocateNodeIDRequest
	(*AllocateNodeIDResponse)(nil), // 1: ducklingdb.proto.AllocateNodeIDResponse
	(*PingRequest)(nil),            // 2: ducklingdb.proto.PingRequest
	(*PingResponse)(nil),           // 3: ducklingdb.proto.PingResponse
	(*SQLRequest)(nil),             // 4: ducklingdb.proto.SQLRequest
	(*SQLRow)(nil),                 // 5: ducklingdb.proto.SQLRow
	(*SQLResponse)(nil),            // 6: ducklingdb.proto.SQLResponse
	(*Info)(nil),                   // 7: ducklingdb.proto.Info
	(*GossipMessage)(nil),          // 8: ducklingdb.proto.GossipMessage
	nil,                            // 9: ducklingdb.proto.GossipMessage.DeltaEntry
	nil,                            // 10: ducklingdb.proto.GossipMessage.HighWaterEntry
	(*Timestamp)(nil),              // 11: ducklingdb.proto.Timestamp
	(*BatchRequest)(nil),           // 12: ducklingdb.proto.BatchRequest
	(*RaftMessage)(nil),            // 13: ducklingdb.proto.RaftMessage
	(*BatchResponse)(nil),          // 14: ducklingdb.proto.BatchResponse
	(*RaftMessageResponse)(nil),    // 15: ducklingdb.proto.RaftMessageResponse
}
var file_internal_proto_service_proto_depIdxs = []int32{
	11, // 0: ducklingdb.proto.PingRequest.server_time:type_name -> ducklingdb.proto.Timestamp
	11, // 1: ducklingdb.proto.PingResponse.server_time:type_name -> ducklingdb.proto.Timestamp
	5,  // 2: ducklingdb.proto.SQLResponse.rows:type_name -> ducklingdb.proto.SQLRow
	9,  // 3: ducklingdb.proto.GossipMessage.delta:type_name -> ducklingdb.proto.GossipMessage.DeltaEntry
	10, // 4: ducklingdb.proto.GossipMessage.high_water:type_name -> ducklingdb.proto.GossipMessage.HighWaterEntry
	7,  // 5: ducklingdb.proto.GossipMessage.DeltaEntry.value:type_name -> ducklingdb.proto.Info
	12, // 6: ducklingdb.proto.Internal.Batch:input_type -> ducklingdb.proto.BatchRequest
	2,  // 7: ducklingdb.proto.Internal.Heartbeat:input_type -> ducklingdb.proto.PingRequest
	0,  // 8: ducklingdb.proto.Internal.AllocateNodeID:input_type -> ducklingdb.proto.AllocateNodeIDRequest
	4,  // 9: ducklingdb.proto.Internal.ExecSQL:input_type -> ducklingdb.proto.SQLRequest
	8,  // 10: ducklingdb.proto.GossipService.Gossip:input_type -> ducklingdb.proto.GossipMessage
	13, // 11: ducklingdb.proto.RaftService.Step:input_type -> ducklingdb.proto.RaftMessage
	14, // 12: ducklingdb.proto.Internal.Batch:output_type -> ducklingdb.proto.BatchResponse
	3,  // 13: ducklingdb.proto.Internal.Heartbeat:output_type -> ducklingdb.proto.PingResponse
	1,  // 14: ducklingdb.proto.Internal.AllocateNodeID:output_type -> ducklingdb.proto.AllocateNodeIDResponse
	6,  // 15: ducklingdb.proto.Internal.ExecSQL:output_type -> ducklingdb.proto.SQLResponse
	8,  // 16: ducklingdb.proto.GossipService.Gossip:output_type -> ducklingdb.proto.GossipMessage
	15, // 17: ducklingdb.proto.RaftService.Step:output_type -> ducklingdb.proto.RaftMessageResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_service_proto_init() }
func file_internal_proto_service_proto_init() {
	if File_internal_proto_service_proto != nil {
		return
	}
	file_internal_proto_api_proto_init()
	file_internal_proto_data_proto_init()
	file_internal_proto_raft_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_service_proto_rawDesc), len(file_internal_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_service_proto_msgTypes,
	}.Build()
	File_internal_proto_service_proto = out.File
	file_internal_proto_service_proto_goTypes = nil
	file_internal_proto_service_proto_depIdxs = nil
}
