// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest carries the sender's identity and current HLC timestamp.
// The receiver uses the timestamp to measure clock offset.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerTime    *Timestamp             `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PingRequest) GetServerTime() *Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// PingResponse carries the responder's identity and current HLC
// timestamp back to the caller.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerTime    *Timestamp             `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PingResponse) GetServerTime() *Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_internal_proto_service_proto protoreflect.FileDescriptor

const file_internal_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/service.proto\x12\x10ducklingdb.proto\x1a\x18internal/proto/api.proto\x1a\x19internal/proto/data.proto\"d\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12<\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1b.ducklingdb.proto.TimestampR\n" +
	"serverTime\"e\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12<\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1b.ducklingdb.proto.TimestampR\n" +
	"serverTime2\xa4\x01\n" +
	"\bInternal\x12J\n" +
	"\x05Batch\x12\x1e.ducklingdb.proto.BatchRequest\x1a\x1f.ducklingdb.proto.BatchResponse\"\x00\x12L\n" +
	"\tHeartbeat\x12\x1d.ducklingdb.proto.PingRequest\x1a\x1e.ducklingdb.proto.PingResponse\"\x00B0Z.github.com/duchm1606/ducklingdb/internal/protob\x06proto3"

var (
	file_internal_proto_service_proto_rawDescOnce sync.Once
	file_internal_proto_service_proto_rawDescData []byte
)

func file_internal_proto_service_proto_rawDescGZIP() []byte {
	file_internal_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_service_proto_rawDesc), len(file_internal_proto_service_proto_rawDesc)))
	})
	return file_internal_proto_service_proto_rawDescData
}

var file_internal_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_service_proto_goTypes = []any{
	(*PingRequest)(nil),   // 0: ducklingdb.proto.PingRequest
	(*PingResponse)(nil),  // 1: ducklingdb.proto.PingResponse
	(*Timestamp)(nil),     // 2: ducklingdb.proto.Timestamp
	(*BatchRequest)(nil),  // 3: ducklingdb.proto.BatchRequest
	(*BatchResponse)(nil), // 4: ducklingdb.proto.BatchResponse
}
var file_internal_proto_service_proto_depIdxs = []int32{
	2, // 0: ducklingdb.proto.PingRequest.server_time:type_name -> ducklingdb.proto.Timestamp
	2, // 1: ducklingdb.proto.PingResponse.server_time:type_name -> ducklingdb.proto.Timestamp
	3, // 2: ducklingdb.proto.Internal.Batch:input_type -> ducklingdb.proto.BatchRequest
	0, // 3: ducklingdb.proto.Internal.Heartbeat:input_type -> ducklingdb.proto.PingRequest
	4, // 4: ducklingdb.proto.Internal.Batch:output_type -> ducklingdb.proto.BatchResponse
	1, // 5: ducklingdb.proto.Internal.Heartbeat:output_type -> ducklingdb.proto.PingResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_service_proto_init() }
func file_internal_proto_service_proto_init() {
	if File_internal_proto_service_proto != nil {
		return
	}
	file_internal_proto_api_proto_init()
	file_internal_proto_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_service_proto_rawDesc), len(file_internal_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_service_proto_msgTypes,
	}.Build()
	File_internal_proto_service_proto = out.File
	file_internal_proto_service_proto_goTypes = nil
	file_internal_proto_service_proto_depIdxs = nil
}
